### ISSUE TITLE
Question: Can I integrate the core in my frontend project? 

### ISSUE THREAD

**Issue by BlueFalcon234** [JNKKKK/NaiveGB#1]
Hey there, I'm planning to make a web based front-end project, sort of like retroarch, but just a fun little project to learn a little about web development and design. While doing a little research, I came across your project and it seem to be a perfectly easy to use backend core, as mentioned the emulator is class it self that can be called. I also loved the motivation which was to help others to understand the Gameboy hardware, to then learn to develop their own Gameboy emulator, which I on plan on doing in the future. I am aware this project is under the MIT license which is a pretty permissive license, but just wanted to ask if it's cool if I can use this as a backend for my front end. I didn't know anywhere else where I could contact you, so I just did it in the issues tab.

Have a great day :)

**Comment by JNKKKK** [comment]
Hi! Yeah feel free to use it in your personal project! Nice to hear that you like it!
